### ISSUE TITLE
undefined-Server memory publish

### ISSUE THREAD

**Issue by foxthefox** [ioBroker/ioBroker.js-controller#1151]
I am not sure if my issue is right in this repo, but something has changed in the past hours.

During the integration tests I get recently only such messages:

```
undefined-Server memory publish system.adapter.fritzdect.0.logLevel {"val":"debug","ack":true,"ts":1609842153088,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153088}
173
undefined-Server Redis Publish State system.adapter.fritzdect.0.logLevel={"val":"debug","ack":true,"ts":1609842153088,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153088}
174
undefined-Server memory publish system.adapter.fritzdect.0.alive {"val":true,"ack":true,"ts":1609842153090,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153090,"expire":true}
175
undefined-Server memory publish system.adapter.fritzdect.0.connected {"val":true,"ack":true,"ts":1609842153090,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153090,"expire":true}
176
undefined-Server memory publish system.adapter.fritzdect.0.memRss {"val":55.91,"ack":true,"ts":1609842153090,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153090}
177
undefined-Server memory publish system.adapter.fritzdect.0.memHeapTotal {"val":33.49,"ack":true,"ts":1609842153090,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153090}
178
undefined-Server memory publish system.adapter.fritzdect.0.memHeapUsed {"val":19.07,"ack":true,"ts":1609842153090,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153090}
179
undefined-Server memory publish system.adapter.fritzdect.0.uptime {"val":0,"ack":true,"ts":1609842153094,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153094}
180
undefined-Server memory publish system.adapter.fritzdect.0.inputCount {"val":2,"ack":true,"ts":1609842153094,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153094}
181
undefined-Server memory publish system.adapter.fritzdect.0.outputCount {"val":8,"ack":true,"ts":1609842153094,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153094}
182
undefined-Server memory publish system.adapter.fritzdect.0.compactMode {"val":false,"ack":true,"ts":1609842153095,"q":0,"from":"system.adapter.fritzdect.0","lc":1609842153095}
```

and these have nothing to do with the adapter implementation I guess.

last successful (18hours ago) test was outputting such logs:
```
memory publish system.adapter.fritzdect.0.logLevel {"val":"debug","ack":true,"ts":1609781016489,"q":0,"from":"system.adapter.fritzdect.0","lc":1609781016489}
165
 Redis Publish State system.adapter.fritzdect.0.logLevel={"val":"debug","ack":true,"ts":1609781016489,"q":0,"from":"system.adapter.fritzdect.0","lc":1609781016489}
166
 memory publish system.adapter.fritzdect.0.alive {"val":true,"ack":true,"ts":1609781016490,"q":0,"from":"system.adapter.fritzdect.0","lc":1609781016490,"expire":true}
```

If I wrongly posted this here, feel free to close the issue immediately.

**Comment by Apollon77** [comment]
This should onyl be in testing right?! We added a missing namespace to one place :-) I check it

**Comment by Apollon77** [comment]
restart tests please.should be fixed

**Comment by foxthefox** [comment]
Its still failing to accomplish the test. Maybe the timing is now different and I have to wait longe for finishing the startup and creation of objects.

but one more observance:
there are always 3 lines when something is published, at least the 3rd line seems to be duplicated
```
Server memory publish fritzdect.0.DECT_grp9CEFB6-3BDCFFC80.state {"val":true,"ack":true,"ts":1609883609111,"q":0,"from":"system.adapter.fritzdect.0","user":"system.user.admin","lc":1609883609111}
41620
Server Redis Publish State fritzdect.0.DECT_grp9CEFB6-3BDCFFC80.state={"val":true,"ack":true,"ts":1609883609111,"q":0,"from":"system.adapter.fritzdect.0","user":"system.user.admin","lc":1609883609111}
41621
Server Redis Publish State fritzdect.0.DECT_grp9CEFB6-3BDCFFC80.state={"val":true,"ack":true,"ts":1609883609111,"q":0,"from":"system.adapter.fritzdect.0","user":"system.user.admin","lc":1609883609111}
41622

```

**Comment by Apollon77** [comment]
I do not know what exactly is wrong (you can also start the tests locally and debug deeper)
In fact I see https://github.com/foxthefox/ioBroker.fritzdect/runs/1652969229#step:6:293 and a stopping of the test adapter directly after these errors which casuses https://github.com/foxthefox/ioBroker.fritzdect/runs/1652969229#step:6:391

That this one line is duplicated can be ignored (reason is in fact now that also the testing framework subscribes to all data as a client and so it is published to that and the adapter, so all good

**Comment by foxthefox** [comment]
I think it is not like that.
The first test with the errors inside is the test which comes out of the box. Check if the adapter is started. hence I do not have the setup of this in my hands, it starts without the mock_server. Which produces the error in the log.

The second test with DECT200 is immediately invoked (which is the first test case in integration.ts), even the adapter is not started yet.
So it breaks. It seems that it does it for each second case.

in local testing all are passed   (24 passing (2m))

**Comment by Apollon77** [comment]
Please give it sometime between the tests ... yes there was a change in the test serversand they need a bit longerto shutdowncorrectly ... make a delay between the tests of lets say 2s

**Comment by AlCalzone** [comment]
Hmm the included test should only run once, so the timeout shouldn't be the reason for that one failing

**Comment by AlCalzone** [comment]
The log @Apollon77 linked does look like the self-defined tests are failing, although I'm not sure why. Or do you have a log line telling us that the built-in test fails?

**Comment by foxthefox** [comment]
@AlCalzone
@Apollon77 

I have made a new reduced setup in terms of only 3 devices and 4 test cases, so the adapter produces not so much debug lines.

What I can see so far:

the built-in test is started and the harness finishes
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:169

then all things starting the adapter is happening, including the error in not possible communication to the Fritzbox.
but adapter is started and evaluation is positive
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:289
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:290
So the built in test is finished and the harness for this will shut down
In my opinion it is finished with shutdown
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:321

before of that finishing the self-defined test are starting:
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:309
the mock server is started (part of before)
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:311

then it seems the second harness is finished
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:350

and the first it() case will be done
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:353
but is stopped immediately
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:354

next harness is created
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:368
finishes the setup 
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:396

and here the adapter is started and communicates with the mockserver
the tests are the processed
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1098
and the result is OK
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1109
the second harness is shutdown and finishes
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1137

the 3rd harness starts and finishes
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1166
immediately, like in the first test case the 3rd it() case is invoked
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1169
and the adapter is not starting and harness immediately shutdown
and finishes probably with
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1177
at this time all gets broken
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1178

with
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1196
https://github.com/foxthefox/ioBroker.fritzdect/runs/1656323212#step:6:1203
it tells a timeout of the f1st and 4th it() case.

My interpretation:
- somehow my before each is not recognized, probably I have too less knowledge how to do it
- the test cases seem to start without the proper delay or even without it
```
						await harness.startAdapterAndWait();
						await delay(3000);
```
- the test cases seem to kept alive in parallel to the next test case, my understanding was the test case needs to run in the timeout and the it fails and the next it() starts

Maybe my code is wrong for the integration.js, but in lack of comparison to other adapters, this is what my knowledge was achieving. Interestingly some days ago everything went even with the 24 test cases well.
Nevertheless I would appreciate if the integration.js would be checked by somebody more knowledgable than me and I appreciate advises.

**Comment by AlCalzone** [comment]
@Apollon77 this is the code in `stopController` that shuts down the DBs:
![grafik](https://user-images.githubusercontent.com/17641229/103781091-28ecdd80-5036-11eb-847c-cbbe345c9425.png)
I guess I now need to await these calls?

**Comment by AlCalzone** [comment]
This **should** be fixed by https://github.com/ioBroker/testing/pull/375, but that PR is not yet ready.

**Comment by Apollon77** [comment]
> I guess I now need to await these calls? 
Yes this is possible in the meantime and should fix it
